package com.tpc.trikride.utils

import com.tpc.trikride.models.FareStop

/**
 * The published FeTODAT fare table, transcribed from the laminated sheet
 * posted by the Federation of Tricycle Operators and Drivers Association of
 * Talibon. Source ordinance amends Section 1 of Municipal Ordinance No.
 * 2018-05 and was enacted on 8 November 2022.
 *
 * This is seed data only. The admin fare screen writes it into the database
 * once, after which the database copy is what the app prices rides from, so
 * corrections happen in the app and not here.
 *
 * Rows carrying a note came out of the photos with a problem: a rate that is
 * lower for seniors than the regular rate, a value cut off at the edge of the
 * frame, or a reading two transcription passes disagreed on. Those are marked
 * needsReview so the admin fare screen can list them, and the ones missing a
 * usable rate start inactive so they cannot price a ride.
 */
object FareSeed {

    /** Zones in the order they appear on the posted sheet. */
    val ZONES = listOf(
        "Balintawak",
        "Santo Nino",
        "San Francisco",
        "San Agustin",
        "Bagacay, Burgos & Rizal",
        "Zamora",
        "San Carlos",
        "Tanghaligue",
        "San Isidro",
        "San Jose",
        "San Pedro",
        "San Roque"
    )

    /** 240 stops across 12 zones. */
    val STOPS: List<FareStop> = listOf(
        FareStop(id = "balintawak__highway_balintawak_to_market", zone = "Balintawak", name = "Highway Balintawak to Market", regularFare = 20.0, discountedFare = 16.0),
        FareStop(id = "balintawak__terminal_titt_to_balintawak", zone = "Balintawak", name = "Terminal (TITT) to Balintawak", regularFare = 20.0, discountedFare = 16.0),
        FareStop(id = "balintawak__garcia_park_ibabaw", zone = "Balintawak", name = "Garcia Park Ibabaw", regularFare = 55.0, discountedFare = 44.0),
        FareStop(id = "balintawak__garcia_park_elementary_school", zone = "Balintawak", name = "Garcia Park Elementary School", regularFare = 45.0, discountedFare = 36.0),
        FareStop(id = "balintawak__tiya_naring_item", zone = "Balintawak", name = "Tiya Naring Item", regularFare = 30.0, discountedFare = 24.0),
        FareStop(id = "balintawak__sergio_auza", zone = "Balintawak", name = "Sergio Auza", regularFare = 25.0, discountedFare = 20.0),
        FareStop(id = "balintawak__balintawak_drier_to_tiya_consing", zone = "Balintawak", name = "Balintawak Drier to Tiya Consing", regularFare = 20.0, discountedFare = 16.0),
        FareStop(id = "balintawak__emmi_rosales", zone = "Balintawak", name = "Emmi Rosales", regularFare = 20.0, discountedFare = 16.0),
        FareStop(id = "balintawak__lorito_crescencio", zone = "Balintawak", name = "Lorito Crescencio", regularFare = 30.0, discountedFare = 24.0),
        FareStop(id = "balintawak__den_den_mosqueda", zone = "Balintawak", name = "Den-Den Mosqueda", regularFare = 30.0, discountedFare = 24.0),
        FareStop(id = "balintawak__jhonrey_polestico", zone = "Balintawak", name = "Jhonrey Polestico", regularFare = 35.0, discountedFare = 28.0),
        FareStop(id = "balintawak__mahogany_pension_house", zone = "Balintawak", name = "Mahogany Pension House", regularFare = 20.0, discountedFare = 16.0),
        FareStop(id = "balintawak__purok_3", zone = "Balintawak", name = "Purok 3", regularFare = 20.0, discountedFare = 16.0),
        FareStop(id = "balintawak__erning_auxtero", zone = "Balintawak", name = "Erning Auxtero", regularFare = 30.0, discountedFare = 24.0),
        FareStop(id = "balintawak__noy_audie_autentico", zone = "Balintawak", name = "Noy Audie Autentico", regularFare = 45.0, discountedFare = 36.0),
        FareStop(id = "balintawak__melchor_polestico", zone = "Balintawak", name = "Melchor Polestico", regularFare = 30.0, discountedFare = 24.0),
        FareStop(id = "balintawak__tiya_doring_valmoria", zone = "Balintawak", name = "Tiya Doring Valmoria", regularFare = 20.0, discountedFare = 16.0),
        FareStop(id = "balintawak__pasulod_purok_6", zone = "Balintawak", name = "Pasulod Purok 6", regularFare = 20.0, discountedFare = 16.0),
        FareStop(id = "balintawak__jun_torreon", zone = "Balintawak", name = "Jun Torreon", regularFare = 30.0, discountedFare = 24.0),
        FareStop(id = "balintawak__purok_7_nia", zone = "Balintawak", name = "Purok 7 NIA", regularFare = 30.0, discountedFare = 24.0),
        FareStop(id = "balintawak__purok_7_kabenic", zone = "Balintawak", name = "Purok 7 (Kabenic)", regularFare = 35.0, discountedFare = 28.0),
        FareStop(id = "balintawak__ka_ano_garcia", zone = "Balintawak", name = "Ka Ano Garcia", regularFare = 20.0, discountedFare = 24.0, needsReview = true, confidence = "Medium", note = "New Rate LOWER than Senior/PWD rate - inverted. Prior transcription flagged 'Uni Auxtero' as the inverted row instead - re-verify against physical sheet."),
        FareStop(id = "balintawak__uni_auxtero", zone = "Balintawak", name = "Uni Auxtero", regularFare = 30.0, discountedFare = 24.0),
        FareStop(id = "balintawak__roque_polestico", zone = "Balintawak", name = "Roque Polestico", regularFare = 20.0, discountedFare = 16.0),
        FareStop(id = "balintawak__bes_gate", zone = "Balintawak", name = "Bes Gate", regularFare = 20.0, discountedFare = 16.0),
        FareStop(id = "balintawak__purok_4_ka_vecenta", zone = "Balintawak", name = "Purok 4 (Ka Vecenta)", regularFare = 25.0, discountedFare = 20.0),
        FareStop(id = "balintawak__purok_4_ka_doring", zone = "Balintawak", name = "Purok 4 (Ka Doring)", regularFare = 20.0, discountedFare = 16.0),
        FareStop(id = "balintawak__purok_2", zone = "Balintawak", name = "Purok 2", regularFare = 30.0, discountedFare = 24.0),
        FareStop(id = "balintawak__purok_1_monticalbo", zone = "Balintawak", name = "Purok 1 (Monticalbo)", regularFare = 25.0, discountedFare = 20.0),
        FareStop(id = "balintawak__purok_1_tiya_naring", zone = "Balintawak", name = "Purok 1 (Tiya Naring)", regularFare = 22.5, discountedFare = 18.0),
        FareStop(id = "balintawak__garcia_park", zone = "Balintawak", name = "Garcia Park", regularFare = 30.0, discountedFare = 24.0),
        FareStop(id = "santo_nino__hi_way_ka_lorna", zone = "Santo Nino", name = "Hi-way Ka Lorna", regularFare = 25.0, discountedFare = 20.0),
        FareStop(id = "santo_nino__lorna_to_mabuhay_kikoy", zone = "Santo Nino", name = "Lorna to Mabuhay/Kikoy", regularFare = 50.0, discountedFare = 40.0),
        FareStop(id = "santo_nino__hi_way_to_ka_buting", zone = "Santo Nino", name = "Hi-way to Ka Buting", regularFare = 30.0, discountedFare = 24.0),
        FareStop(id = "santo_nino__buting_to_ka_poloy", zone = "Santo Nino", name = "Buting to Ka Poloy", regularFare = 35.0, discountedFare = 28.0),
        FareStop(id = "santo_nino__poloy_to_ka_garitoy", zone = "Santo Nino", name = "Poloy to Ka Garitoy", regularFare = 40.0, discountedFare = 32.0),
        FareStop(id = "santo_nino__garitoy_to_ka_cario", zone = "Santo Nino", name = "Garitoy to Ka Cario", regularFare = 50.0, discountedFare = 40.0),
        FareStop(id = "santo_nino__hi_way_to_coop", zone = "Santo Nino", name = "Hi-way to Coop", regularFare = 35.0, discountedFare = 28.0),
        FareStop(id = "santo_nino__coop_to_ka_sherley", zone = "Santo Nino", name = "Coop to Ka Sherley", regularFare = 40.0, discountedFare = 32.0),
        FareStop(id = "santo_nino__sherly_to_ka_kasto", zone = "Santo Nino", name = "Sherly to Ka Kasto", regularFare = 50.0, discountedFare = 40.0),
        FareStop(id = "santo_nino__kastor_to_ka_francis", zone = "Santo Nino", name = "Kastor to Ka Francis", regularFare = 60.0, discountedFare = 48.0),
        FareStop(id = "santo_nino__hi_way_to_ka_timo", zone = "Santo Nino", name = "Hi-way to Ka Timo", regularFare = 40.0, discountedFare = 32.0),
        FareStop(id = "santo_nino__timot_to_ka_eting", zone = "Santo Nino", name = "Timot to Ka Eting", regularFare = 50.0, discountedFare = 40.0),
        FareStop(id = "santo_nino__eting_to_ka_pedio", zone = "Santo Nino", name = "Eting to Ka Pedio", regularFare = 60.0, discountedFare = 48.0),
        FareStop(id = "santo_nino__pedio_to_ka_frank", zone = "Santo Nino", name = "Pedio to Ka Frank", regularFare = 65.0, discountedFare = 52.0),
        FareStop(id = "santo_nino__santo_nino_hs", zone = "Santo Nino", name = "Santo Nino HS", regularFare = 35.0, discountedFare = 28.0),
        FareStop(id = "santo_nino__sto_nino_hs_to_ka_alice", zone = "Santo Nino", name = "Sto. Nino HS to Ka Alice", regularFare = 40.0, discountedFare = 32.0),
        FareStop(id = "santo_nino__alice_to_beracha_eyog", zone = "Santo Nino", name = "Alice to Beracha/Eyog", regularFare = 50.0, discountedFare = 40.0),
        FareStop(id = "santo_nino__beracha_eyog_to_ka_piling", zone = "Santo Nino", name = "Beracha/Eyog to Ka Piling", regularFare = 60.0, discountedFare = 48.0),
        FareStop(id = "santo_nino__piling_to_ka_camilo", zone = "Santo Nino", name = "Piling to Ka Camilo", regularFare = 70.0, discountedFare = 56.0),
        FareStop(id = "santo_nino__highway_to_ka_melencio", zone = "Santo Nino", name = "Highway to Ka Melencio", regularFare = 35.0, discountedFare = 28.0),
        FareStop(id = "santo_nino__melecio_to_ka_rina", zone = "Santo Nino", name = "Melecio to Ka Rina", regularFare = 40.0, discountedFare = 32.0),
        FareStop(id = "santo_nino__rina_to_ka_jimmy", zone = "Santo Nino", name = "Rina to Ka Jimmy", regularFare = 50.0, discountedFare = 40.0),
        FareStop(id = "santo_nino__jimmy_to_ka_esoy", zone = "Santo Nino", name = "Jimmy to Ka Esoy", regularFare = 60.0, discountedFare = 48.0),
        FareStop(id = "santo_nino__ka_rina_to_lomboy", zone = "Santo Nino", name = "Ka Rina to Lomboy", regularFare = 50.0, discountedFare = 40.0),
        FareStop(id = "santo_nino__lomboy_to_ka_paran", zone = "Santo Nino", name = "Lomboy to Ka Paran", regularFare = 50.0, discountedFare = 40.0),
        FareStop(id = "santo_nino__paran_to_basurahan", zone = "Santo Nino", name = "Paran to Basurahan", regularFare = 80.0, discountedFare = 64.0),
        FareStop(id = "santo_nino__lomboy_to_ka_kilita", zone = "Santo Nino", name = "Lomboy to Ka Kilita", regularFare = 70.0, discountedFare = 56.0),
        FareStop(id = "santo_nino__highway_to_ka_nanong", zone = "Santo Nino", name = "Highway to Ka Nanong", regularFare = 45.0, discountedFare = 36.0),
        FareStop(id = "santo_nino__nanong_to_ka_gorio", zone = "Santo Nino", name = "Nanong to Ka Gorio", regularFare = 50.0, discountedFare = 40.0),
        FareStop(id = "santo_nino__highway_to_ka_porton", zone = "Santo Nino", name = "Highway to Ka Porton", regularFare = 35.0, discountedFare = 28.0),
        FareStop(id = "santo_nino__highway_to_ka_nigro", zone = "Santo Nino", name = "Highway to Ka Nigro", regularFare = 40.0, discountedFare = 32.0),
        FareStop(id = "santo_nino__nigro_to_panagbuan", zone = "Santo Nino", name = "Nigro to Panagbuan", regularFare = 50.0, discountedFare = 40.0),
        FareStop(id = "santo_nino__highway_to_kamomot", zone = "Santo Nino", name = "Highway to Kamomot", regularFare = 35.0, discountedFare = 28.0),
        FareStop(id = "santo_nino__momot_to_polin_misyang", zone = "Santo Nino", name = "Momot to Polin/Misyang", regularFare = 40.0, discountedFare = 32.0),
        FareStop(id = "santo_nino__highway_to_sitio_lapak", zone = "Santo Nino", name = "Highway to Sitio Lapak", regularFare = 35.0, discountedFare = 28.0),
        FareStop(id = "santo_nino__highway_to_ka_ciling", zone = "Santo Nino", name = "Highway to Ka Ciling", regularFare = 35.0, discountedFare = 28.0),
        FareStop(id = "santo_nino__ciling_to_sitio_sun_ok", zone = "Santo Nino", name = "Ciling to Sitio Sun-ok", regularFare = 35.0, discountedFare = 28.0),
        FareStop(id = "santo_nino__highway_to_ka_fred", zone = "Santo Nino", name = "Highway to Ka Fred", regularFare = 35.0, discountedFare = 28.0),
        FareStop(id = "san_francisco__lising", zone = "San Francisco", name = "Lising", regularFare = 20.0, discountedFare = 16.0),
        FareStop(id = "san_francisco__lantay_boys", zone = "San Francisco", name = "Lantay Boys", regularFare = 20.0, discountedFare = 16.0),
        FareStop(id = "san_francisco__centro", zone = "San Francisco", name = "Centro", regularFare = 20.0, discountedFare = 16.0),
        FareStop(id = "san_francisco__eskina_frank", zone = "San Francisco", name = "Eskina Frank", regularFare = 20.0, discountedFare = 16.0),
        FareStop(id = "san_francisco__coop", zone = "San Francisco", name = "Coop", regularFare = 20.0, discountedFare = 16.0, needsReview = true, confidence = "Medium", note = "DISPUTED: this photo reads 16/20; prior transcription session read 24/30 for this row. Re-verify against physical sheet."),
        FareStop(id = "san_francisco__taytay", zone = "San Francisco", name = "Taytay", regularFare = 30.0, discountedFare = 24.0, needsReview = true, confidence = "Medium", note = "DISPUTED: this photo reads 24/30; prior transcription session read 32/40 for this row. Re-verify against physical sheet."),
        FareStop(id = "san_francisco__sitio_panabang", zone = "San Francisco", name = "Sitio Panabang", regularFare = 40.0, discountedFare = 32.0, needsReview = true, confidence = "Medium", note = "DISPUTED: this photo reads 32/40; prior transcription session read 48/60 for this row. Re-verify against physical sheet."),
        FareStop(id = "san_francisco__tumoy_tabon", zone = "San Francisco", name = "Tumoy Tabon", regularFare = 60.0, discountedFare = 48.0, needsReview = true, confidence = "Medium", note = "DISPUTED: this photo reads 48/60; prior transcription session read 32/40 for this row. Re-verify against physical sheet."),
        FareStop(id = "san_francisco__ka_turo_suan", zone = "San Francisco", name = "Ka Turo Suan", regularFare = 40.0, discountedFare = 32.0, needsReview = true, confidence = "Medium", note = "DISPUTED: this photo reads 32/40; prior transcription session read 24/30 for this row. Re-verify against physical sheet."),
        FareStop(id = "san_francisco__eskina_ka_boboy_tessie", zone = "San Francisco", name = "Eskina Ka Boboy Tessie", regularFare = 30.0, discountedFare = 24.0, needsReview = true, confidence = "Medium", note = "DISPUTED: this photo reads 24/30; prior transcription session read 32/40 for this row. Re-verify against physical sheet."),
        FareStop(id = "san_francisco__gisok", zone = "San Francisco", name = "Gisok", regularFare = 40.0, discountedFare = 32.0, needsReview = true, confidence = "Medium", note = "DISPUTED: this photo reads 32/40; prior transcription session read 24/30 for this row. Re-verify against physical sheet."),
        FareStop(id = "san_francisco__baybay", zone = "San Francisco", name = "Baybay", regularFare = 30.0, discountedFare = 24.0),
        FareStop(id = "san_francisco__bacbacan", zone = "San Francisco", name = "Bacbacan", regularFare = 30.0, discountedFare = 24.0),
        FareStop(id = "san_francisco__carusos_area", zone = "San Francisco", name = "Carusos Area", regularFare = 30.0, discountedFare = 24.0),
        FareStop(id = "san_francisco__boy_mamie", zone = "San Francisco", name = "Boy Mamie", regularFare = 30.0, discountedFare = 24.0),
        FareStop(id = "san_francisco__sitio_panabang_2nd_entry", zone = "San Francisco", name = "Sitio Panabang (2nd entry)", regularFare = 40.0, discountedFare = 32.0, needsReview = true, confidence = "Medium", note = "Duplicate stop name with a different rate than the earlier 'Sitio Panabang' row - possibly two distinct sitio locations sharing a name, or a misread. Verify."),
        FareStop(id = "san_francisco__health_center", zone = "San Francisco", name = "Health Center", regularFare = 30.0, discountedFare = 24.0),
        FareStop(id = "san_francisco__la_purisima_chapel", zone = "San Francisco", name = "La Purisima Chapel", regularFare = 30.0, discountedFare = 24.0),
        FareStop(id = "san_francisco__prk_6_san_vicente_chapel", zone = "San Francisco", name = "Prk 6 San Vicente Chapel", regularFare = 40.0, discountedFare = 32.0),
        FareStop(id = "san_francisco__edgar_anita_water_refilling_turo", zone = "San Francisco", name = "Edgar Anita Water-Refilling Turo", regularFare = 40.0, discountedFare = 32.0),
        FareStop(id = "san_francisco__turo_fish_port", zone = "San Francisco", name = "Turo Fish Port", regularFare = 50.0, discountedFare = 40.0),
        FareStop(id = "san_agustin__pob_to_purok_7", zone = "San Agustin", name = "Pob. to Purok 7", regularFare = 20.0, discountedFare = 16.0),
        FareStop(id = "san_agustin__san_agustine_parish_church", zone = "San Agustin", name = "San Agustine Parish Church", regularFare = 30.0, discountedFare = 24.0),
        FareStop(id = "san_agustin__castor_prk5_prk6", zone = "San Agustin", name = "Castor (Prk5-Prk6)", regularFare = 30.0, discountedFare = 24.0),
        FareStop(id = "san_agustin__crossing_prk6_ka_lita", zone = "San Agustin", name = "Crossing (Prk6 Ka Lita)", regularFare = 40.0, discountedFare = 32.0),
        FareStop(id = "san_agustin__ka_tita_dam_ka_mario", zone = "San Agustin", name = "Ka Tita-Dam Ka Mario", regularFare = 40.0, discountedFare = 32.0),
        FareStop(id = "san_agustin__ka_cielo_tongo", zone = "San Agustin", name = "Ka Cielo (Tongo)", regularFare = 40.0, discountedFare = 32.0),
        FareStop(id = "san_agustin__ka_pilto_kalahi_lokso_on", zone = "San Agustin", name = "Ka Pilto (Kalahi Lokso-on)", regularFare = 40.0, discountedFare = 32.0),
        FareStop(id = "san_agustin__highway_sa_agustine", zone = "San Agustin", name = "Highway sa Agustine", regularFare = 30.0, discountedFare = 24.0),
        FareStop(id = "san_agustin__cirilo", zone = "San Agustin", name = "Cirilo", regularFare = 25.0, discountedFare = 20.0),
        FareStop(id = "san_agustin__centro_purok3", zone = "San Agustin", name = "Centro (Purok3)", regularFare = 30.0, discountedFare = 24.0),
        FareStop(id = "san_agustin__bunso", zone = "San Agustin", name = "Bunso", regularFare = 30.0, discountedFare = 24.0),
        FareStop(id = "san_agustin__sudlon", zone = "San Agustin", name = "Sudlon", regularFare = 40.0, discountedFare = 32.0),
        FareStop(id = "san_agustin__purok_4", zone = "San Agustin", name = "Purok 4", regularFare = 30.0, discountedFare = 24.0),
        FareStop(id = "san_agustin__centro_purok_4_lugsong", zone = "San Agustin", name = "Centro Purok 4/Lugsong", regularFare = 35.0, discountedFare = 28.0),
        FareStop(id = "san_agustin__munumento_pcpg_ancestral_park", zone = "San Agustin", name = "Munumento (PCPG Ancestral Park)", regularFare = 30.0, discountedFare = 24.0),
        FareStop(id = "san_agustin__ka_victor", zone = "San Agustin", name = "Ka Victor", regularFare = 40.0, discountedFare = 32.0),
        FareStop(id = "bagacay_burgos_rizal__bagacay_highway", zone = "Bagacay, Burgos & Rizal", name = "Bagacay Highway", regularFare = 40.0, discountedFare = 32.0),
        FareStop(id = "bagacay_burgos_rizal__burgos_highway", zone = "Bagacay, Burgos & Rizal", name = "Burgos Highway", regularFare = 45.0, discountedFare = 36.0),
        FareStop(id = "bagacay_burgos_rizal__bagacay_purok_5", zone = "Bagacay, Burgos & Rizal", name = "Bagacay Purok 5", regularFare = 50.0, discountedFare = 40.0),
        FareStop(id = "bagacay_burgos_rizal__bagacay_highschool", zone = "Bagacay, Burgos & Rizal", name = "Bagacay Highschool", regularFare = 50.0, discountedFare = 40.0),
        FareStop(id = "bagacay_burgos_rizal__bagacay_lapay", zone = "Bagacay, Burgos & Rizal", name = "Bagacay Lapay", regularFare = 60.0, discountedFare = 48.0),
        FareStop(id = "bagacay_burgos_rizal__bagacay_burawin", zone = "Bagacay, Burgos & Rizal", name = "Bagacay Burawin", regularFare = 70.0, discountedFare = 56.0),
        FareStop(id = "bagacay_burgos_rizal__namong", zone = "Bagacay, Burgos & Rizal", name = "Namong", regularFare = 45.0, discountedFare = 36.0),
        FareStop(id = "bagacay_burgos_rizal__bagacay_pantalan", zone = "Bagacay, Burgos & Rizal", name = "Bagacay Pantalan", regularFare = 50.0, discountedFare = 40.0),
        FareStop(id = "bagacay_burgos_rizal__baracuda", zone = "Bagacay, Burgos & Rizal", name = "Baracuda", regularFare = 50.0, discountedFare = 40.0),
        FareStop(id = "bagacay_burgos_rizal__namong_purok_2", zone = "Bagacay, Burgos & Rizal", name = "Namong Purok 2", regularFare = 50.0, discountedFare = 40.0),
        FareStop(id = "bagacay_burgos_rizal__bagacay_lambayan", zone = "Bagacay, Burgos & Rizal", name = "Bagacay Lambayan", regularFare = 50.0, discountedFare = 40.0),
        FareStop(id = "bagacay_burgos_rizal__mga_sudlonon_sa_burgos", zone = "Bagacay, Burgos & Rizal", name = "Mga Sudlonon sa Burgos", regularFare = 45.0, discountedFare = 36.0),
        FareStop(id = "bagacay_burgos_rizal__rizal", zone = "Bagacay, Burgos & Rizal", name = "Rizal", regularFare = 100.0, discountedFare = 80.0),
        FareStop(id = "bagacay_burgos_rizal__burgos_purok_1_2_3", zone = "Bagacay, Burgos & Rizal", name = "Burgos Purok 1, 2, 3", regularFare = 50.0, discountedFare = 40.0),
        FareStop(id = "bagacay_burgos_rizal__burgos_purok_4_5", zone = "Bagacay, Burgos & Rizal", name = "Burgos Purok 4, 5", regularFare = 70.0, discountedFare = 56.0),
        FareStop(id = "bagacay_burgos_rizal__burgos_purok_7", zone = "Bagacay, Burgos & Rizal", name = "Burgos Purok 7", regularFare = 80.0, discountedFare = 64.0),
        FareStop(id = "zamora__sambag", zone = "Zamora", name = "Sambag", regularFare = 50.0, discountedFare = 40.0),
        FareStop(id = "zamora__tonggoto_resing", zone = "Zamora", name = "Tonggoto Resing", regularFare = 50.0, discountedFare = 40.0),
        FareStop(id = "zamora__nia_office_to_patring", zone = "Zamora", name = "NIA Office to Patring", regularFare = 60.0, discountedFare = 48.0),
        FareStop(id = "zamora__san_vicente_village_dicong", zone = "Zamora", name = "San Vicente Village-Dicong", regularFare = 60.0, discountedFare = 48.0),
        FareStop(id = "zamora__pina_lydia_roping", zone = "Zamora", name = "Pina-Lydia Roping", regularFare = 60.0, discountedFare = 48.0),
        FareStop(id = "zamora__pablo_daring_demit", zone = "Zamora", name = "Pablo-Daring-Demit", regularFare = 80.0, discountedFare = 64.0),
        FareStop(id = "zamora__iglesia", zone = "Zamora", name = "Iglesia", regularFare = 45.0, discountedFare = 36.0),
        FareStop(id = "zamora__ka_pedring", zone = "Zamora", name = "Ka Pedring", regularFare = 45.0, discountedFare = 36.0),
        FareStop(id = "zamora__san_vicente_village", zone = "Zamora", name = "San Vicente Village", regularFare = 52.5, discountedFare = 42.0),
        FareStop(id = "zamora__ka_dicong", zone = "Zamora", name = "Ka Dicong", regularFare = 52.5, discountedFare = 42.0),
        FareStop(id = "zamora__ka_pating", zone = "Zamora", name = "Ka Pating", regularFare = 52.5, discountedFare = 42.0),
        FareStop(id = "zamora__ka_lydia", zone = "Zamora", name = "Ka Lydia", regularFare = 52.5, discountedFare = 42.0),
        FareStop(id = "zamora__ka_roping", zone = "Zamora", name = "Ka Roping", regularFare = 52.5, discountedFare = 42.0),
        FareStop(id = "zamora__ka_dito", zone = "Zamora", name = "Ka Dito", regularFare = 60.0, discountedFare = 48.0),
        FareStop(id = "zamora__ka_tolding", zone = "Zamora", name = "Ka Tolding", regularFare = 60.0, discountedFare = 48.0),
        FareStop(id = "zamora__ka_vestre", zone = "Zamora", name = "Ka Vestre", regularFare = 60.0, discountedFare = 48.0),
        FareStop(id = "zamora__ka_helario", zone = "Zamora", name = "Ka Helario", regularFare = 60.0, discountedFare = 48.0),
        FareStop(id = "zamora__bagasaak", zone = "Zamora", name = "Bagasaak", regularFare = 67.5, discountedFare = 54.0),
        FareStop(id = "zamora__tonggo", zone = "Zamora", name = "Tonggo", regularFare = 37.5, discountedFare = 30.0),
        FareStop(id = "zamora__ka_dory", zone = "Zamora", name = "Ka Dory", regularFare = 45.0, discountedFare = 36.0),
        FareStop(id = "zamora__ka_sendoy", zone = "Zamora", name = "Ka Sendoy", regularFare = 45.0, discountedFare = 36.0),
        FareStop(id = "zamora__ka_patring", zone = "Zamora", name = "Ka Patring", regularFare = 52.5, discountedFare = 42.0),
        FareStop(id = "san_carlos__ka_eklat", zone = "San Carlos", name = "Ka Eklat", regularFare = 30.0, discountedFare = 24.0, needsReview = true, confidence = "Low", note = "Photo is sideways/skewed - row/value alignment not fully certain."),
        FareStop(id = "san_carlos__ka_ester", zone = "San Carlos", name = "Ka Ester", regularFare = 30.0, discountedFare = 24.0, needsReview = true, confidence = "Low", note = "Photo is sideways/skewed - row/value alignment not fully certain."),
        FareStop(id = "san_carlos__ver_polo", zone = "San Carlos", name = "Ver Polo", regularFare = 37.5, discountedFare = 30.0, needsReview = true, confidence = "Low", note = "Photo is sideways/skewed - row/value alignment not fully certain."),
        FareStop(id = "san_carlos__centro", zone = "San Carlos", name = "Centro", regularFare = 45.0, discountedFare = 36.0, needsReview = true, confidence = "Low", note = "Photo is sideways/skewed - row/value alignment not fully certain."),
        FareStop(id = "san_carlos__purok_6", zone = "San Carlos", name = "Purok 6", regularFare = 45.0, discountedFare = 36.0, needsReview = true, confidence = "Low", note = "Photo is sideways/skewed - row/value alignment not fully certain."),
        FareStop(id = "san_carlos__purok_3", zone = "San Carlos", name = "Purok 3", regularFare = 45.0, discountedFare = 36.0, needsReview = true, confidence = "Low", note = "Photo is sideways/skewed - row/value alignment not fully certain."),
        FareStop(id = "san_carlos__purok_4", zone = "San Carlos", name = "Purok 4", regularFare = 37.5, discountedFare = 30.0, needsReview = true, confidence = "Low", note = "Photo is sideways/skewed - row/value alignment not fully certain."),
        FareStop(id = "san_carlos__purok_5", zone = "San Carlos", name = "Purok 5", regularFare = 45.0, discountedFare = 36.0, needsReview = true, confidence = "Low", note = "Photo is sideways/skewed - row/value alignment not fully certain."),
        FareStop(id = "san_carlos__salod_here", zone = "San Carlos", name = "Salod Here", regularFare = 37.5, discountedFare = 30.0, needsReview = true, confidence = "Low", note = "Photo is sideways/skewed - row/value alignment not fully certain."),
        FareStop(id = "san_carlos__nestor_cita", zone = "San Carlos", name = "Nestor Cita", regularFare = 37.5, discountedFare = 30.0, needsReview = true, confidence = "Low", note = "Photo is sideways/skewed - row/value alignment not fully certain."),
        FareStop(id = "tanghaligue__tanghaligue_highway", zone = "Tanghaligue", name = "Tanghaligue Highway", regularFare = 35.0, discountedFare = 28.0, needsReview = true, confidence = "Low", note = "Stop names historically obscured by a binding tag on the laminated sheet; row alignment uncertain due to photo skew."),
        FareStop(id = "tanghaligue__tikoy_mercy", zone = "Tanghaligue", name = "Tikoy/Mercy", regularFare = 70.0, discountedFare = 56.0, needsReview = true, confidence = "Low", note = "Name partly obscured by binding tag."),
        FareStop(id = "tanghaligue__tikoy_hener", zone = "Tanghaligue", name = "Tikoy/Hener", regularFare = 70.0, discountedFare = 56.0, needsReview = true, confidence = "Low", note = "Name partly obscured by binding tag."),
        FareStop(id = "tanghaligue__eskina_pablo_pablo_balay", zone = "Tanghaligue", name = "Eskina Pablo/Pablo Balay", regularFare = 70.0, discountedFare = 56.0, confidence = "Low"),
        FareStop(id = "tanghaligue__centro_ingkoy_terio", zone = "Tanghaligue", name = "Centro/Ingkoy Terio", regularFare = 80.0, discountedFare = 64.0, confidence = "Low"),
        FareStop(id = "tanghaligue__eskina_galingan_inkoy_terio", zone = "Tanghaligue", name = "Eskina Galingan-Inkoy Terio", regularFare = 100.0, discountedFare = 80.0, confidence = "Low"),
        FareStop(id = "tanghaligue__centro_purok2_suba", zone = "Tanghaligue", name = "Centro/Purok2/Suba", regularFare = 70.0, discountedFare = 56.0, confidence = "Low"),
        FareStop(id = "tanghaligue__centro_osoy", zone = "Tanghaligue", name = "Centro/Osoy", regularFare = 100.0, discountedFare = 80.0, confidence = "Low"),
        FareStop(id = "tanghaligue__waka_konek", zone = "Tanghaligue", name = "Waka/Konek", regularFare = 150.0, discountedFare = 120.0, confidence = "Low"),
        FareStop(id = "tanghaligue__eskina_waka_to_vilma", zone = "Tanghaligue", name = "Eskina Waka to Vilma", regularFare = 100.0, discountedFare = 80.0, confidence = "Low"),
        FareStop(id = "tanghaligue__eskina_waka_to_aleg", zone = "Tanghaligue", name = "Eskina Waka to Aleg", regularFare = 70.0, discountedFare = 56.0, confidence = "Low"),
        FareStop(id = "tanghaligue__eskina_waka_to_silay", zone = "Tanghaligue", name = "Eskina Waka to Silay", regularFare = 70.0, discountedFare = 56.0, confidence = "Low"),
        FareStop(id = "tanghaligue__waka_ating", zone = "Tanghaligue", name = "Waka/Ating", regularFare = 80.0, discountedFare = 64.0, confidence = "Low"),
        FareStop(id = "tanghaligue__waka_to_hene_cajes", zone = "Tanghaligue", name = "Waka to Hene Cajes", regularFare = 60.0, discountedFare = 48.0, confidence = "Low"),
        FareStop(id = "san_isidro__penticostal", zone = "San Isidro", name = "Penticostal", regularFare = 20.0, discountedFare = 16.0, confidence = "Medium"),
        FareStop(id = "san_isidro__resty_ricemill", zone = "San Isidro", name = "Resty (Ricemill)", regularFare = 25.0, discountedFare = 20.0, confidence = "Medium"),
        FareStop(id = "san_isidro__domingo_sulod", zone = "San Isidro", name = "Domingo (Sulod)", regularFare = 25.0, discountedFare = 20.0, confidence = "Medium"),
        FareStop(id = "san_isidro__cadanoy_sulod", zone = "San Isidro", name = "Cadanoy (Sulod)", regularFare = 25.0, discountedFare = 20.0, confidence = "Medium"),
        FareStop(id = "san_isidro__penie_sulod", zone = "San Isidro", name = "Penie (Sulod)", regularFare = 25.0, discountedFare = 20.0, confidence = "Medium"),
        FareStop(id = "san_isidro__centro", zone = "San Isidro", name = "Centro", regularFare = 25.0, discountedFare = 20.0, confidence = "Medium"),
        FareStop(id = "san_isidro__nabunturan", zone = "San Isidro", name = "Nabunturan", regularFare = 25.0, discountedFare = 20.0, confidence = "Medium"),
        FareStop(id = "san_isidro__san_isidro_high_school", zone = "San Isidro", name = "San Isidro High School", regularFare = 25.0, discountedFare = 20.0, confidence = "Medium"),
        FareStop(id = "san_isidro__eduardo_arcana_sulod", zone = "San Isidro", name = "Eduardo Arcana (Sulod)", regularFare = 30.0, discountedFare = 24.0, confidence = "Medium"),
        FareStop(id = "san_isidro__kahayag_bbc", zone = "San Isidro", name = "Kahayag BBC", regularFare = 25.0, discountedFare = 20.0, confidence = "Medium"),
        FareStop(id = "san_isidro__luis_bebie", zone = "San Isidro", name = "Luis Bebie", regularFare = 30.0, discountedFare = 24.0, confidence = "Medium"),
        FareStop(id = "san_isidro__eskina_rudy_minda_sulod", zone = "San Isidro", name = "Eskina Rudy-Minda (Sulod)", regularFare = 25.0, discountedFare = 20.0, confidence = "Medium"),
        FareStop(id = "san_isidro__rudy_minda_sulod", zone = "San Isidro", name = "Rudy-Minda (Sulod)", regularFare = 25.0, discountedFare = 20.0, confidence = "Medium"),
        FareStop(id = "san_isidro__acasia", zone = "San Isidro", name = "Acasia", regularFare = 25.0, discountedFare = 20.0, needsReview = true, confidence = "Low", note = "From here on, row/value alignment gets harder to confirm - page skew and glare."),
        FareStop(id = "san_isidro__tpc", zone = "San Isidro", name = "TPC", regularFare = 25.0, discountedFare = 20.0, confidence = "Low"),
        FareStop(id = "san_isidro__jbc", zone = "San Isidro", name = "JBC", regularFare = 25.0, discountedFare = 20.0, confidence = "Low"),
        FareStop(id = "san_isidro__new_ihawan", zone = "San Isidro", name = "New Ihawan", regularFare = 30.0, discountedFare = 24.0, confidence = "Low"),
        FareStop(id = "san_isidro__muslim_area", zone = "San Isidro", name = "Muslim Area", regularFare = 25.0, discountedFare = 20.0, confidence = "Low"),
        FareStop(id = "san_isidro__cogao", zone = "San Isidro", name = "Cogao", regularFare = 25.0, discountedFare = 20.0, confidence = "Low"),
        FareStop(id = "san_isidro__cogao_chapel", zone = "San Isidro", name = "Cogao Chapel", regularFare = 30.0, discountedFare = 24.0, confidence = "Low"),
        FareStop(id = "san_isidro__cogao_bbc", zone = "San Isidro", name = "Cogao BBC", regularFare = 35.0, discountedFare = 28.0, confidence = "Low"),
        FareStop(id = "san_isidro__cogao_tumoy", zone = "San Isidro", name = "Cogao Tumoy", regularFare = 40.0, discountedFare = 32.0, confidence = "Low"),
        FareStop(id = "san_isidro__samco", zone = "San Isidro", name = "Samco", regularFare = 25.0, discountedFare = 20.0, confidence = "Low"),
        FareStop(id = "san_isidro__adec_sulod", zone = "San Isidro", name = "Adec (Sulod)", regularFare = 30.0, discountedFare = 24.0, confidence = "Low"),
        FareStop(id = "san_isidro__eskina_molit", zone = "San Isidro", name = "Eskina Molit", regularFare = 40.0, discountedFare = 32.0, confidence = "Low"),
        FareStop(id = "san_isidro__mar_auguis", zone = "San Isidro", name = "Mar Auguis", regularFare = 30.0, discountedFare = 32.0, needsReview = true, confidence = "Low", note = "New Rate LOWER than Senior/PWD rate - inverted, consistent with the prior transcription's flag on this same row."),
        FareStop(id = "san_isidro__agree", zone = "San Isidro", name = "Agree", regularFare = 45.0, discountedFare = 36.0, confidence = "Low"),
        FareStop(id = "san_isidro__jr_carmen", zone = "San Isidro", name = "Jr Carmen", regularFare = 40.0, discountedFare = 32.0, confidence = "Low"),
        FareStop(id = "san_isidro__thomas", zone = "San Isidro", name = "Thomas", regularFare = 45.0, discountedFare = 36.0, confidence = "Low"),
        FareStop(id = "san_isidro__melecio_rose", zone = "San Isidro", name = "Melecio-Rose", regularFare = 35.0, discountedFare = 28.0, confidence = "Low"),
        FareStop(id = "san_isidro__titing_garcia", zone = "San Isidro", name = "Titing Garcia", regularFare = 40.0, discountedFare = 32.0, confidence = "Low"),
        FareStop(id = "san_isidro__tayatayan_naupa", zone = "San Isidro", name = "Tayatayan Naupa", regularFare = 0.0, discountedFare = 0.0, active = false, needsReview = true, confidence = "Low", note = "Cut off at edge of photo - no fare visible."),
        FareStop(id = "san_jose__braulio", zone = "San Jose", name = "Braulio", regularFare = 20.0, discountedFare = 16.0, needsReview = true, confidence = "Low", note = "Photo sideways/skewed."),
        FareStop(id = "san_jose__coop", zone = "San Jose", name = "Coop", regularFare = 25.0, discountedFare = 20.0, needsReview = true, confidence = "Low", note = "Photo sideways/skewed."),
        FareStop(id = "san_jose__heyong", zone = "San Jose", name = "Heyong", regularFare = 30.0, discountedFare = 24.0, needsReview = true, confidence = "Low", note = "Photo sideways/skewed."),
        FareStop(id = "san_jose__vilma", zone = "San Jose", name = "Vilma", regularFare = 25.0, discountedFare = 20.0, needsReview = true, confidence = "Low", note = "Photo sideways/skewed."),
        FareStop(id = "san_jose__dayan", zone = "San Jose", name = "Dayan", regularFare = 40.0, discountedFare = 32.0, needsReview = true, confidence = "Low", note = "Photo sideways/skewed."),
        FareStop(id = "san_jose__pat", zone = "San Jose", name = "Pat", regularFare = 25.0, discountedFare = 20.0, needsReview = true, confidence = "Low", note = "Photo sideways/skewed."),
        FareStop(id = "san_jose__talibon_integrated_bus_terminal_tibt", zone = "San Jose", name = "Talibon Integrated Bus Terminal (TIBT)", regularFare = 20.0, discountedFare = 16.0, needsReview = true, confidence = "Low", note = "Photo sideways/skewed."),
        FareStop(id = "san_jose__hospital_gmph", zone = "San Jose", name = "Hospital (GMPH)", regularFare = 20.0, discountedFare = 16.0, needsReview = true, confidence = "Low", note = "Photo sideways/skewed."),
        FareStop(id = "san_jose__galingan_hener", zone = "San Jose", name = "Galingan Hener", regularFare = 30.0, discountedFare = 24.0, needsReview = true, confidence = "Low", note = "Photo sideways/skewed."),
        FareStop(id = "san_jose__pablo", zone = "San Jose", name = "Pablo", regularFare = 35.0, discountedFare = 28.0, needsReview = true, confidence = "Low", note = "Photo sideways/skewed."),
        FareStop(id = "san_jose__panabang", zone = "San Jose", name = "Panabang", regularFare = 30.0, discountedFare = 24.0, needsReview = true, confidence = "Low", note = "Photo sideways/skewed."),
        FareStop(id = "san_jose__eklat", zone = "San Jose", name = "Eklat", regularFare = 35.0, discountedFare = 28.0, needsReview = true, confidence = "Low", note = "Photo sideways/skewed."),
        FareStop(id = "san_jose__lupa", zone = "San Jose", name = "Lupa", regularFare = 25.0, discountedFare = 20.0, needsReview = true, confidence = "Low", note = "Photo sideways/skewed."),
        FareStop(id = "san_jose__centro_fatima", zone = "San Jose", name = "Centro Fatima", regularFare = 35.0, discountedFare = 28.0, needsReview = true, confidence = "Low", note = "Photo sideways/skewed."),
        FareStop(id = "san_pedro__pandan", zone = "San Pedro", name = "Pandan", regularFare = 20.0, discountedFare = 16.0, confidence = "Medium"),
        FareStop(id = "san_pedro__garcia_street", zone = "San Pedro", name = "Garcia Street", regularFare = 25.0, discountedFare = 16.0, needsReview = true, confidence = "Medium", note = "Rate jump (16 -> 25) is a larger multiple than typical for this zone's other rows - double check."),
        FareStop(id = "san_pedro__centro", zone = "San Pedro", name = "Centro", regularFare = 20.0, discountedFare = 16.0, confidence = "Medium"),
        FareStop(id = "san_pedro__sitio_seawall_pasulod", zone = "San Pedro", name = "Sitio Seawall (Pasulod)", regularFare = 20.0, discountedFare = 20.0, needsReview = true, confidence = "Medium", note = "Senior/PWD rate equals New Rate - no discount applied, unusual versus rest of sheet."),
        FareStop(id = "san_pedro__sitio_dagohoy_kalsada", zone = "San Pedro", name = "Sitio Dagohoy (Kalsada)", regularFare = 25.0, discountedFare = 16.0, confidence = "Medium"),
        FareStop(id = "san_pedro__sitio_dagohoy_pasulod", zone = "San Pedro", name = "Sitio Dagohoy (Pasulod)", regularFare = 20.0, discountedFare = 20.0, needsReview = true, confidence = "Medium", note = "Senior/PWD rate equals New Rate - no discount applied, unusual versus rest of sheet."),
        FareStop(id = "san_pedro__barangay_hall", zone = "San Pedro", name = "Barangay Hall", regularFare = 25.0, discountedFare = 16.0, confidence = "Medium"),
        FareStop(id = "san_pedro__dagohoy_beach", zone = "San Pedro", name = "Dagohoy Beach", regularFare = 20.0, discountedFare = 16.0, confidence = "Medium"),
        FareStop(id = "san_pedro__spv", zone = "San Pedro", name = "SPV", regularFare = 25.0, discountedFare = 20.0, confidence = "Medium"),
        FareStop(id = "san_pedro__nay_saya_sulod", zone = "San Pedro", name = "Nay Saya (Sulod)", regularFare = 25.0, discountedFare = 20.0, confidence = "Medium"),
        FareStop(id = "san_pedro__boy_helen_sulod", zone = "San Pedro", name = "Boy Helen (Sulod)", regularFare = 25.0, discountedFare = 20.0, confidence = "Medium"),
        FareStop(id = "san_roque__merideth", zone = "San Roque", name = "Merideth", regularFare = 40.0, discountedFare = 32.0),
        FareStop(id = "san_roque__gelyn_romy", zone = "San Roque", name = "Gelyn/Romy", regularFare = 40.0, discountedFare = 32.0),
        FareStop(id = "san_roque__gabriel_dina", zone = "San Roque", name = "Gabriel & Dina", regularFare = 40.0, discountedFare = 36.0),
        FareStop(id = "san_roque__dancy", zone = "San Roque", name = "Dancy", regularFare = 45.0, discountedFare = 56.0, needsReview = true, note = "New Rate LOWER than Senior/PWD rate - inverted."),
        FareStop(id = "san_roque__dina_gabril", zone = "San Roque", name = "Dina/Gabril", regularFare = 0.0, discountedFare = 0.0, active = false, needsReview = true, note = "Source shows New Rate = 740.00, which breaks pattern against every neighboring row (all P20-100). Almost certainly a typo/misprint. Do not use this value without verifying the original ordinance."),
        FareStop(id = "san_roque__me_me", zone = "San Roque", name = "Me-Me", regularFare = 50.0, discountedFare = 42.0),
        FareStop(id = "san_roque__roy", zone = "San Roque", name = "Roy", regularFare = 60.0, discountedFare = 48.0),
        FareStop(id = "san_roque__lapas_ka_roy_to_centro_liaya", zone = "San Roque", name = "Lapas ka Roy to Centro Liaya", regularFare = 40.0, discountedFare = 32.0),
        FareStop(id = "san_roque__centro_to_victor", zone = "San Roque", name = "Centro to Victor", regularFare = 50.0, discountedFare = 40.0),
        FareStop(id = "san_roque__emiliana_edie_edwin", zone = "San Roque", name = "Emiliana/Edie/Edwin", regularFare = 50.0, discountedFare = 40.0),
        FareStop(id = "san_roque__latayan_dam", zone = "San Roque", name = "Latayan/Dam", regularFare = 60.0, discountedFare = 48.0),
        FareStop(id = "san_roque__arlen_to_centro_special_trip", zone = "San Roque", name = "Arlen to Centro (Special Trip)", regularFare = 60.0, discountedFare = 80.0, needsReview = true, note = "New Rate LOWER than Senior/PWD rate - inverted."),
        FareStop(id = "san_roque__punso_vicenta_basurahan", zone = "San Roque", name = "Punso/Vicenta/Basurahan", regularFare = 100.0, discountedFare = 56.0),
        FareStop(id = "san_roque__edig_modesta_centro_arba", zone = "San Roque", name = "Edig/Modesta/Centro Arba", regularFare = 70.0, discountedFare = 64.0),
        FareStop(id = "san_roque__zesa", zone = "San Roque", name = "Zesa", regularFare = 0.0, discountedFare = 80.0, active = false, needsReview = true, note = "New Rate cut off at bottom of photo.")
    )
}
